type IconNames =
    'cross'
    | 'chevron-down'
    | 'check'
    | 'eye'
    | 'crossed-out-eye'
    | 'arrow-left'
    | 'location'
    | 'link'
    | 'calendar'
    | 'logo'
    | 'home'
    | 'profile'
    | 'other'
    | 'spinner'
    | 'add-photo'
    | 'trash-bin'
    | 'heart'

export default IconNames
